sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t jaredzhang09/webapp .

script:
    - docker run -e CI=true jaredzhang09/webapp npm run test -- --coverage

